Update update_and_create_pr.yml

diff --git a/.github/workflows/update_and_create_pr.yml b/.github/workflows/update_and_create_pr.yml
--- a/.github/workflows/update_and_create_pr.yml
+++ b/.github/workflows/update_and_create_pr.yml
@@ -19,9 +19,20 @@ jobs:
         with:
           token: ${{ secrets.PAT_TOKEN }}
 
+      - name: Ensure required inputs are set
+        run: |
+          if [ -z "${{ github.event.inputs.path }}" ]; then
+            echo "Path input is required"
+            exit 1
+          fi
+          if [ -z "${{ github.event.inputs.title }}" ]; then
+            echo "Title input is required"
+            exit 1
+          fi
+
       - name: Display file content before changes
         run: cat .docs/${{ github.event.inputs.path }}
-    
+
       - name: Update Document
         run: |
           DATE=$(date +%Y-%m-%d)
@@ -48,10 +59,6 @@ jobs:
           body: "This PR updates the last reviewed date for the document."
           delete-branch: true
           draft: false
-
-      
-    
-
 
       - name: Auto Merge
         uses: pascalgn/automerge-action@v0.14.3
